server:
  host: 127.0.0.1
  port: 9090

Redis:
  host: 127.0.0.1
  port: 6379

Mysql:
  host: 127.0.0.1
  port: 3306
  password: root
  dbname: douyin
  user: root


#这里是视频存储的本地地址
localfile:
  path: D:/videos/